[pytest]
addopts = --tb=short --maxfail=1 --disable-warnings
pythonpath =
    firmware/circuitpython
    firmware/circuitpython/lib

markers =
    mpy: tests that require optional mpy-cross build lane
