"""Temporary code.py: one bounded, read-only BM83 version fingerprint.

Back up the existing entrypoints before any deployment. This wrapper delegates
to the unchanged production main.py/lib, disables autoreload, and adds DEBUG
device ticks. Restore the prior entrypoint and reload after the capture. DEBUG
changes timing; version replies cannot establish audible recovery.

Only opcode 0x08 is generated by the probe. Types 00/01 are standard baseline
queries; 03/04/05 depend on firmware and the vendor support tables conflict.
Every type gets at most one attempt, with no reset, reconnect, power action,
EEPROM write, or retry on a missing/rejected/invalid reply. Normal production
traffic and user controls continue, including RX and event ACK handling.
The caller must leave the BM83 powered. Readiness uses recently validated UART
events, which show UART responsiveness, not physical ON or an audio session.
The probe never changes production power state to manufacture confirmation.
"""
import time

import supervisor

from utils import common
from utils.ticks import ticks_add, ticks_diff, ticks_less, ticks_ms

_PROBE_USED = False
_VERSION_TYPES = (0x00, 0x01, 0x03, 0x04, 0x05)
_REPLY_LENGTHS = (3, 3, 5, 5, 4)  # Parameters: type byte plus version bytes.
_READY_TIMEOUT_MS = 30000
_SETTLE_MS = 2000
_EVENT_FRESH_MS = 2250  # Two seconds plus one query-gap of scheduling grace.
_QUERY_TIMEOUT_MS = 2000
_QUERY_GAP_MS = 250


def _bench_dprint(*args):
    # The observer logs every version body once, including late/unmatched data.
    if args and isinstance(args[0], str) and args[0].startswith("[BM83 EVT] op=0x18 "):
        return
    if common.DEBUG:
        print("[BENCH ticks_ms=%d]" % supervisor.ticks_ms(), *args)


def _hex(data):
    return " ".join("%02X" % b for b in data)


class VersionProbe:
    """Observe ACK and typed version reply independently, without consuming RX."""

    def __init__(self, bm):
        global _PROBE_USED
        self.bm = bm
        self.phase = "done" if _PROBE_USED else "waiting"
        _PROBE_USED = True
        self.index = 0
        self.deadline = ticks_add(ticks_ms(), _READY_TIMEOUT_MS)
        self.stable_since = None
        self.last_event_at = None
        self.ack = None
        self.reply = None
        self.failure = None
        self.ack_ambiguous = False
        self.cancel_reason = None
        self.results = []
        self.log("one probe per interpreter; leave BM83 powered; waiting for fresh, settled UART events")
        self.log("UART readiness does not prove physical ON; production power state is unchanged")

    def log(self, *args):
        print("[VERSION_PROBE ticks_ms=%d]" % ticks_ms(), *args)

    def eligible(self):
        bm = self.bm
        return (not bm._explicit_off and bm._power_state is None
                and not bm._power_confirm_deadline)

    def event_fresh(self, now):
        return (self.last_event_at is not None
                and 0 <= ticks_diff(now, self.last_event_at) <= _EVENT_FRESH_MS)

    def observe(self, op, params):
        if op == 0x18:
            self.log("RX event=18 raw:", _hex(params), "phase:", self.phase)
        elif op == 0x00 and params and params[0] == 0x08:
            # ACK carries no type tag; retain its status separately from data.
            self.log("ACK opcode=08 raw:", _hex(params), "status:", params[1] if len(params) == 2 else "invalid",
                     "active_type:",
                     "%02X" % _VERSION_TYPES[self.index] if self.phase == "query" else "none")
        elif op == 0x01 and params and params[0] == 0x00 and self.phase != "done":
            self.cancel_reason = "chip OFF observed"
        if self.phase != "query" or not ticks_less(ticks_ms(), self.deadline):
            return
        if op == 0x00 and params and params[0] == 0x08:
            self._observe_ack(params)
        elif op == 0x18 and params and params[0] == _VERSION_TYPES[self.index]:
            self._observe_reply(params)

    def _observe_ack(self, params):
        if len(params) != 2:
            self.ack_ambiguous = True
            self.failure = "invalid command ACK length"
            return
        if self.ack is not None and self.ack != params[1]:
            self.ack_ambiguous = True
            self.failure = "conflicting command ACK statuses"
        self.ack = params[1]
        if self.ack != 0:
            self.failure = "command rejected (ACK %02X)" % self.ack

    def _observe_reply(self, params):
        if len(params) != _REPLY_LENGTHS[self.index]:
            self.failure = "matching type has invalid reply length"
        elif self.reply is not None and self.reply != bytes(params):
            self.failure = "conflicting matching replies"
        else:
            self.reply = bytes(params)

    def record(self, outcome, reason):
        typ = _VERSION_TYPES[self.index]
        self.results.append((typ, outcome, self.ack, self.reply, reason))
        self.log("RESULT type=%02X" % typ, outcome, "ACK:", self.ack,
                 "typed reply retained:", self.reply is not None, "reason:", reason)
        if outcome == "OBSERVED":
            self.log("version fields:", tuple(self.reply[1:]))
            if typ == 0x05:
                self.log("project ASCII rendering:", "".join(chr(b) if 32 <= b < 127 else "?"
                                                             for b in self.reply[1:]))
        self.index += 1

    def stop(self, reason):
        while self.index < len(_VERSION_TYPES):
            self.record("INCONCLUSIVE", reason)
            self.ack = None
            self.reply = None
        self.phase = "done"
        self.log("finished; no automatic repeat on Power ON/OFF")

    def start_query(self):
        self.ack = None
        self.reply = None
        self.failure = None
        self.ack_ambiguous = False
        self.phase = "query"
        self.deadline = ticks_add(ticks_ms(), _QUERY_TIMEOUT_MS)
        typ = _VERSION_TYPES[self.index]
        self.log("TX opcode=08 type=%02X (one attempt)" % typ)
        try:
            self.bm.send(0x08, bytes((typ,)))
        except Exception as error:
            self.failure = "send failed: " + str(error)

    def finish_query(self, outcome, reason):
        self.record(outcome, reason)
        if self.index == len(_VERSION_TYPES):
            self.phase = "done"
            self.log("finished; no automatic repeat on Power ON/OFF")
        else:
            self.ack = None
            self.reply = None
            self.phase = "gap"
            self.deadline = ticks_add(ticks_ms(), _QUERY_GAP_MS)

    def tick(self):
        if self.phase == "done":
            return
        now = ticks_ms()
        bm = self.bm
        if self.cancel_reason or bm._explicit_off or bm._power_state == "off_press":
            self.stop(self.cancel_reason or "explicit user OFF")
        elif self.phase == "waiting":
            self.tick_waiting(now)
        elif not self.eligible():
            self.stop("power changed during version probe")
        elif self.phase == "gap":
            if not ticks_less(now, self.deadline):
                if self.event_fresh(now):
                    self.start_query()
                else:
                    self.stop("validated UART event stale before next query")
        else:
            self.tick_query(now)

    def tick_waiting(self, now):
        if not ticks_less(now, self.deadline):
            self.stop("fresh UART readiness not settled within readiness deadline")
        elif not self.eligible() or not self.event_fresh(now):
            self.stable_since = None
        elif self.stable_since is None:
            self.stable_since = ticks_add(now, _SETTLE_MS)
        elif not ticks_less(now, self.stable_since):
            self.start_query()

    def tick_query(self, now):
        if self.failure:
            if self.ack_ambiguous or self.ack is None:
                self.stop(self.failure + "; ACK unresolved, remaining probes skipped")
            else:
                self.finish_query("INCONCLUSIVE", self.failure)
        elif self.ack == 0 and self.reply is not None:
            self.finish_query("OBSERVED", "ACK accepted plus matching typed reply")
        elif not ticks_less(now, self.deadline):
            if self.ack is None:
                # No type is carried in ACK: a delayed ACK cannot safely be
                # assigned to a later query after an unresolved timeout.
                self.stop("timeout waiting for command ACK; remaining probes skipped")
            else:
                self.finish_query("INCONCLUSIVE", "timeout waiting for matching typed reply")


def make_bench_type(base):
    """Add observation/ticking while preserving every production control method."""
    class BenchBm83(base):
        __slots__ = ("_version_probe",)

        def __init__(self, uart=None):
            base.__init__(self, uart)
            self._version_probe = VersionProbe(self)

        def tick_power(self):
            base.tick_power(self)
            self._version_probe.tick()

        def poll(self, max_read=768, max_events=8):
            events = base.poll(self, max_read=max_read, max_events=max_events)
            if events:
                # Timestamp parsed/checksummed frames only; bytes, liveness
                # caches, and power_on cannot establish probe readiness.
                self._version_probe.last_event_at = ticks_ms()
            for op, params in events:
                self._version_probe.observe(op, params)
            return events

    return BenchBm83


def run():
    supervisor.runtime.autoreload = False
    common.dprint = _bench_dprint
    common.DEBUG = True
    import bm83 as package
    from bm83 import bm83 as driver
    bench_type = make_bench_type(driver.Bm83)
    driver.Bm83 = bench_type
    package.Bm83 = bench_type
    print("[BENCH] Read-only version queries once; unsupported/timeouts are INCONCLUSIVE")
    print("[BENCH] Leave BM83 powered: recent UART events are readiness, not ON confirmation")
    print("[BENCH] DEBUG changes timing; restore entrypoint and reload after capture")
    import main as firmware_main
    try:
        firmware_main.main()
    except Exception as error:
        try:
            import traceback
            print("[FATAL]", error)
            traceback.print_exception(error)
        except Exception:
            print("[FATAL]", error)
        while True:
            time.sleep(1)


if __name__ == "__main__":
    run()
